#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

PROG=/usr/sbin/airportald

service_triggers()
{
	procd_add_reload_trigger airportal firewall network wireless
	procd_add_interface_trigger "interface.*" guest /etc/init.d/airportal reload
}

start_service()
{
	local enabled

	config_load airportal
	config_get_bool enabled global enabled 1
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="4096 4096"
	procd_close_instance
}

reload_service()
{
	procd_send_signal airportal '*' HUP
}
